default:
  control_regions: [cr_w, cr_t, cr_z]
  fixed_backgrounds: [other]
  validation_regions: []
  signal_regions: [signal]
  systematics: [jer, c, b, u, t, trigger, somesyst, zjets_theory]
  signal_systematics: [sigsyst]

nosyst:
  control_regions: [cr_w, cr_t, cr_z]
  fixed_backgrounds: [other]
  signal_regions: [signal]
  systematics: []
